
class FundException(Exception):
    pass

class ReviewException(Exception):
    pass